### PR TITLE
bumped version of gql_code_builder

### PR DESCRIPTION
**Pull request by WDtms**
Current version cant be used in app's with analyzer 2.0.0

This update will fix this

### CODE REVIEW

**Comment by budde377** [comment]
Thanks for your contribution!

**Comment by budde377** [comment]
Sorry, I had to revert it again. Can you elaborate on what you mean by not working with analyzer?

**Comment by WDtms** [comment]
> Sorry, I had to revert it again. Can you elaborate on what you mean by not working with analyzer?

```Because graphql_codegen >=0.0.1-alpha.2 depends on gql_code_builder ^0.2.0 which depends on analyzer ^1.2.0, graphql_codegen >=0.0.1-alpha.2 requires analyzer ^1.2.0.
So, because dizraptor depends on both analyzer ^2.2.0 and graphql_codegen ^0.4.8, version solving failed.
pub get failed (1; So, because dizraptor depends on both analyzer ^2.2.0 and graphql_codegen ^0.4.8, version solving failed.)```

**Comment by budde377** [comment]
@WDtms, I've published a new version with the alpha dependency (0.5.0-alpha.0)

**Pull request merged**
