### PR TITLE
bump: gql: ^0.14.0 / gql_code_builder: ^0.6.0 FOR analyzer: >=4.0.0 <6.0.0

### PR DESCRIPTION
**Pull request by seanolsen**
- bump gql: ^0.14.0
- bump gql_code_builder: ^0.6.0

### CODE REVIEW

**Comment by budde377** [comment]
It looks like the dependencies don't play well together, please update them and try again.

**Comment by seanolsen** [comment]
@budde377 fixed deps in example

**Comment by budde377** [comment]
@seanolsen still failing :(

**Comment by budde377** [comment]
You can take a look at the github action and run the test locally for faster turnaround.

**Comment by seanolsen** [comment]
> You can take a look at the github action and run the test locally for faster turnaround.
this time it should work

**Comment by seanolsen** [comment]
@budde377 I think theres some errors in code checks
I didn't made any changes in file packages/graphql_switch/example/lib/switch.dart

**Pull request merged**
